dataset: open_meteo
base_url: https://archive-api.open-meteo.com/v1/archive
format: JSON

filters:
  time: [2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026]

storage:
  raw_path: data/raw/open_meteo
  silver_path: data/silver/open_meteo
  gold_path: data/gold/open_meteo
